import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "./components/Tailwindindicator";
import Head from "next/head"; // Import Head component


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abisentry Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.png" /> {<link rel="icon" type="image/png" sizes="3x3" href="/favicon.png" />}
      </Head>
      <body className={`${inter.className} bg-[#191919]`}>
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
